name: Production Build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build project and deploy to S3
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 15.14.0
      uses: actions/setup-node@v3
      with:
        node-version: "15.14.0"
    - name: npm Install
      run: npm install
    - name: npm run build
      run: npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT : ${{ secrets.AWS_S3_ENDPOINT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
